name: Terraform Plan and Apply

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ main ]

defaults:
  run:
    shell: bash -ieo pipefail {0} # loads the .bashrc file

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::288533909336:role/github-actions-oidc
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=plan
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false plan
