name: Terraform Destroy

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ main ]

defaults:
  run:
    shell: bash -ieo pipefail {0} # loads the .bashrc file

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::288533909336:role/github-actions-oidc
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve -destroy -input=false
        env:
          TF_VAR_argocd_cloudflare_token: ${{ secrets.TF_VAR_CLOUDFLARE_TOKEN }}
          TF_VAR_argocd_ingress_auth: ${{ secrets.TF_VAR_INGRESS_AUTH }}
          TF_VAR_rackspace_spot_token: ${{ secrets.TF_VAR_RACKSPACE_SPOT_TOKEN }}
